# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
  secret_key_base: 'ea35bb13af7d65d5ea22e11f5952d17e3e1e184412eb2d4b991d78076ff796824614f8812a9c3f00348915c04bfc3cfc2f512aaef65f044da132e5e51910ec16'
#   twitter_consumer_key: 'Rd5s5s82FAiUD1KufnrnQ'
#   twitter_consumer_secret: '6q8LouMcq8qE1aZa5Mn5nONdwpzchrmXOIlqEYl9CU'

# test:
#   secret_key_base: 'ea35bb13af7d65d5ea22e11f5952d17e3e1e184412eb2d4b991d78076ff796824614f8812a9c3f00348915c04bfc3cfc2f512aaef65f044da132e5e51910ec16'
#   twitter_consumer_key: 'Rd5s5s82FAiUD1KufnrnQ'
#   twitter_consumer_secret: '6q8LouMcq8qE1aZa5Mn5nONdwpzchrmXOIlqEYl9CU'

production:
  secret_key_base: '02051f6389c1fc43d5452918143c1fae024c429bf32bb6f91f93f31314c86ed59e7d7b5324774d9521dfc6148078f3543c1377ea3400475eedb0205b59fb3b65'
  # twitter_consumer_key: 'Rd5s5s82FAiUD1KufnrnQ'
  # twitter_consumer_secret: '6q8LouMcq8qE1aZa5Mn5nONdwpzchrmXOIlqEYl9CU'
